### ISSUE TITLE
Minified widget.js? 

### ISSUE THREAD

**Issue by sudma** [abletech/addressfinder-magento#19]
When JS minification is enabled the endpoint for minified widget.js file returns 404

Minified file URL https://api.addressfinder.io/assets/v3/widget.min.js does not exist.

Do you maybe have in plan to allow the minified file version of 
https://api.addressfinder.io/assets/v3/widget.js 

Thank you.

**Comment by 1mattramsay** [comment]
This is now fixed. 
 https://api.addressfinder.io/assets/v3/widget.min.js has been created and will load when called.
