### ISSUE TITLE
How can I configure this to be NZ only mode with use nearby locations and add custom JS?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [abletech/addressfinder-magento#21]
Hello,

I do not have a Country select box on the checkout as the store only services one country NZ, the widget appears to be defaulting to AU.

This module is all minified so I can't easily debug any chance of releasing non minified?
As I would also like to add a custom JS handler to do something with the meta data x,y location.
selected by the user such as.

```js
function onNZAddressSelected(selectedAddress, metaData) {
  console.log(metaData.x, metaData.y);

  // Probably a better way.
$(this.element).parent().parent().parent().parent().parent().find("input[name=af_x]").val(metaData.x);
$(this.element).parent().parent().parent().parent().parent().find("input[name=af_y]").val(metaData.y);
}

widget.nz.on('result:select', onNZAddressSelected);
```

I have done this before with an older version, of the widget which seems to have since disappeared from github.

Previous was: addressfinder/module-magento2 version 1.1.1

window.AddressFinder._magentoPlugin.widgetConfig shows an AU Key is configured.

Could you please point me in the right direction to make these kinds of configurations if possible?

Kind regards,

**Comment by katenorquay** [comment]
Hi! Sorry for the delayed response.
1. Default country issue:  How are you removing the country select box from the checkout? Our plugin determines which country to use from the country select box, so the fact that you have Australia active makes me think that the select is still on the page hidden with css perhaps, and the defaultCountry is set to Australia in the Stores -> General -> Country Options panel. If you had no country select box at all you would get no results. If this is not your scenario let us know so we can replicate it, we would like to fix this issue.
2. Custom JS issue: Currently, you can't add a custom js handler for the address selected event, but may expose this method in the future
3. I'll discuss with the team if we want to release the non-minified js, or expose it in debug mode in some way. I'll keep you updated in this thread.

**Comment by LiamKarlMitchell** [comment]
Hi @katenorquay ,

Thanks for the reply,

We don't need the country select box for the site so it was removed with a plugin to be one less thing for the user to deal with when ordering to reduce complexity.

Amasty One Step Checkout was used, it can add/remove/move inputs.

I think it was not hidden with css but completely removed although it might have made a hidden input I do not recall. Can check if that helps?

The plugin defaults to AU if not set/found, maybe if we can disable a country specifically rather than relying on the country select?

I ended up just adapting the older Address Finder plugin which I still had the code for on another server, but being able to customize to get at the lat/lng data is quite useful we are using it to select the nearest store for extra information against the order/customer.

Would be super if we could have an option save the lat/lng data against the customers address as well. I attempted this but couldn't seem to get it to behave.

**Comment by katenorquay** [comment]
Hi @LiamKarlMitchell it would be helpful if you could post a link to the website if possible. The plugin doesn't actually default to AU if there's no country select, it defaults to null, so you wouldn't see any results. But since you are seeing AU results there must be something else going on.

I'll try installing Amasty One Step Checkout and see if I can reproduce the issue.

**Comment by katenorquay** [comment]
@LiamKarlMitchell, can you confirm that your stores default country is new zealand in the config?
<img width="1010" alt="Screen Shot 2019-10-17 at 5 14 27 PM" src="https://user-images.githubusercontent.com/20099672/66977276-cc846200-f101-11e9-8c83-f4e21720f7fb.png">

**Comment by LiamKarlMitchell** [comment]
Hi @katenorquay , yes that was the case sorry for the delay in responding.
I ended up just switching to the old version of the extension.

I am now setting this up on another new website which is NZ only and still has the country dropdown set-up. Don't want to share address yet because of bots etc.

Will post here again if have same problem but I figure that if we end up hiding the country select box with CSS visibility: none or display:none maybe it will work just fine.

Thanks :)

**Comment by LiamKarlMitchell** [comment]
Don't hard-code forCountry('AU') use the configured default country.

**Comment by bencorlett** [comment]
This isn’t exactly correct, but you’re observing a side effect of fetching states for Australia when you don’t have Australia enabled. I’ll take a look at this soon and prepare a bug fix.

Thanks!

Sent from my iPad

Please excuse my brevity
