### ISSUE TITLE
State Mapping

### ISSUE THREAD

**Issue by bencorlett** [abletech/addressfinder-magento#22]
Hey all :)

I can see that a [recent update](https://github.com/abletech/addressfinder-magento/blob/develop/src/address_form_config/state_mappings.js#L2-L9) was aimed at selecting regions/states when they're presented as a dropdown. This code makes an assumption of the internal identifier for each state, IDs `569` through to `575`. In a standard Magento installation where there are no additional regions/states are added are actually `512` through to `519`. Irrespective of this, I don't think we can rely on the internal identifier for the most part:

![Screen Shot 2019-09-04 at 2 00 11 pm](https://user-images.githubusercontent.com/181919/64224820-51356b00-cf1c-11e9-9539-eb69a3d837a2.png)

```html
<select class="select" name="region_id" id="O2G8HJQ" aria-describedby="notice-O2G8HJQ" placeholder="">
    <option value="">Please select a region, state or province.</option>
    <option data-title="Australian Capital Territory" value="512">Australian Capital Territory</option>
    <option data-title="New South Wales" value="513">New South Wales</option>
    <option data-title="Northern Territory" value="514">Northern Territory</option>
    <option data-title="Queensland" value="515">Queensland</option>
    <option data-title="South Australia" value="516">South Australia</option>
    <option data-title="Tasmania" value="517">Tasmania</option>
    <option data-title="Victoria" value="518">Victoria</option>
    <option data-title="Western Australia" value="519">Western Australia</option>
</select>
```

In the [Magento 1](https://github.com/abletech/addressfinder-magento-1/) extension, I introduced the concept of [**transformers**](https://github.com/abletech/addressfinder-magento-1/blob/master/js/addressfinder/src/magento.js#L260-L285
). These are arbitrary and are used to transform a value returning from the AddressFinder API (e.g. **New South Wales**) into a value within Magento (e.g. **513**, or **570**, whatever it is in each installation).

We passed the transformer configuration [through from server-side](https://github.com/abletech/addressfinder-magento-1/blob/master/app/design/frontend/base/default/template/addressfinder/customer/address/form.phtml#L23-L28), by pulling out all regions/state mappings.

It might require a sizeable refactor to inject this configuration into the Magento 2 extension. Happy to explore this idea, have you got a preference on the way you'd like to attack it?

 - Ben.

**Comment by 1mattramsay** [comment]
Hi Ben,
It looks like there are a few variations of these state values (512-519, 569-576 & 485-592) so your solution is certainly the best option. Thanks
