### ISSUE TITLE
Magento source maps

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-magento#28]
The Magento plugin code is currently all minified in the browser, which makes it difficult for anyone except us to debug it. This is not great for open source.

A good solution is to use sourcemaps. This is a special file that connects a minified/uglified version of an asset to the original authored version. You can set this as an option for webpack. There is no performance hit because sourcemaps don't get loaded unless you have dev tools open. This would make it easier for both us and other users to debug 🎉

There are two steps
1. Export the non-minified addressfinder-webpage-tools package by. This file can be minified by the plugins themselves.
2. Add sourcemaps to the webpack config of each of the plugins. There is an example of this already in the WooCommerce plugin.

The changes themselves are small, but testing and deploying will take a while since we are changing the minification process of the webpage tools, and deploying to 3 different platforms

**Comment by LiamKarlMitchell** [comment]
Could release the clean source? its not like it has special or secret logic to protect the Address Finder site has great examples and a generator and its really just the glue to add it to the Magneto inputs.

https://github.com/abletech/addressfinder-magento/blob/develop/view/frontend/web/js/magento-plugin.js is already uglified/processed by webpack.

Not a big deal just would have been helpful for our niche need to add something custom to it :)

**Comment by bencorlett** [comment]
This has been implemented in #40.
