### ISSUE TITLE
Browser autocomplete gets in the way sometimes?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [abletech/addressfinder-magento#34]
Might be a question for the Address Finder end but.

Is there a way to prevent web browser address auto complete to enforce using Address Finder or to make it play nicer?

**Comment by LiamKarlMitchell** [comment]
Interesting info on this here.
Can prevent autofill on the entire form. (Not great)
WebKit browsers have the pesudo-class :-webkit-autofill which matches when an element has its value autofilled.

On change event not initiated by Address Finder Plugin, could detect this class, re-look it up in address finder if not the same, and show the address finder dialog?

```js
if ($("#textbox").is(":-webkit-autofill")) 
{    
    // the value in the input field of the form was filled in with google chrome autocomplete
}
```
Note: Above JS may have a syntax error/exception? in some browsers so should ensure its webkit.

**Comment by katenorquay** [comment]
Which browser have you been seeing this on? We try to always turn off the autocomplete but it can be a bit of a moving target

**Comment by LiamKarlMitchell** [comment]
Google chrome has its own address auto complete, which gets used that fills out the address boxes, then address finder is not used.

**Comment by katenorquay** [comment]
Hi @LiamKarlMitchell, I have put in a card to investigate this, but yeah it is more an addressfinder question than specific to this plugin. I will close this issue, but I'll let you know if we find a fix
