### ISSUE TITLE
Magento 2 - updates to fix state mapping and mutiple payments

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-magento#45]
Testing issues:

1. I couldn't get the updates to work on Magento v2.1. In the system.log this error is thrown:
<img width="1327" alt="Screen Shot 2019-12-10 at 1 08 48 PM" src="https://user-images.githubusercontent.com/20099672/70483733-58d56300-1b4e-11ea-8068-6e1779918ab8.png">

Seems like the problem is to do with the country variable:
`$country = $this->countryInformationAcquirer->getCountryInfo($countryCode);`
@bencorlett any ideas?

2. RESOLVED: For Australian addresses, the suburb value is being populated into a different field. Normally, we add suburb values to the 'city' field, but now it is added to the 'street[2]' field. The image shows 'YAAPEET' in the street[2] field, and the city from a previous New Zealand address I searched remains in the city field.
<img width="526" alt="Screen Shot 2019-12-10 at 12 19 09 PM" src="https://user-images.githubusercontent.com/20099672/70482134-8e2b8200-1b49-11ea-8827-34a36e2ac819.png">

**Comment by bencorlett** [comment]
@katenorquay  That's interesting. In my testing within Magento 2.1 it seems to work just fine. My assumption is that it might be related to what regions were installed. Do you know if this was a NZ-based thing?

**Comment by katenorquay** [comment]
@bencorlett I'm not sure. How would I find out?
