### ISSUE TITLE
Magento 2.3 compatibility?

### ISSUE THREAD

**Issue by sudma** [AbleTech/addressfinder-magento#5]
The module does not seem to be compatible with Magento 2.3 version.

As per dependency for _magento/framework_ in composer.json
`magento/framework: 100.0.*|100.1.*|101.0.*`

Running `composer require addressfinder/module-magento2` command breaks. 
![2019-02-11-11-10](https://user-images.githubusercontent.com/6605787/52557002-7a5ea480-2dee-11e9-9e5d-b0e310ca529b.png)

**Comment by 1mattramsay** [comment]
Hi Sudma,
Thanks for letting us know. We are looking into this currently and hope to have a solution soon.
