### ISSUE TITLE
Magento plugin issues - single line 'widget options' issue in the admin config.

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-magento#51]
The parser isn't handling multi line entries to the widget options

@1mattramsay, this one has also been resolved by Ben's updates so I will close 👍

**Comment by bencorlett** [comment]
Could you throw an example in?

**Comment by katenorquay** [comment]
@bencorlett don't worry about this - this was an old card from our backlog but I just investigated and it seems our previous updates have resolved it

**Comment by bencorlett** [comment]
Oh good! I thought as much, that we're handling those JSON widget options much more safely now. We also [validate the JSON](https://github.com/abletech/addressfinder-magento/blob/develop/Model/WidgetConfigProvider.php#L84-L104) prior to passing it through to AF :)
