### ISSUE TITLE
Incorrect layout selector for Shipping checkout

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-magento#56]
Our layout selectors are looking for 'li#opc-shipping_method' and 'li#payment' but we have found a customer who has 'div#opc-shipping_method' and 'div#payment' elements. AddressFinder does not work for this customer.

Could these selectors be updated to just '#opc-shipping_method' and '#payment'?

**Comment by bencorlett** [comment]
This is for the standard checkout or a third party module?

I’d suggest we create another form for this, but I don’t believe we are officially supporting third party modules?
