### ISSUE TITLE
Too many mutations prevent AddressFinder from working? identifiedFormHelperConfig is empty array.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [abletech/addressfinder-magento#59]
When debug mode is switched on I see this console log.

```Page is triggering a large amount of mutations, which may prevent AddressFinder from working, and will slow down your store.```

Sorry I don't quite understand what this means, would someone be able to elobrate?

This time it is on a Magento 2.3.2 website with a WeltPixel theme installed via composer from this documentation.
https://addressfinder.nz/docs/magento/

Address lookup does not appear to be working, although they could have modified the checkout form/template, is this mutations warning onto something here or can I ignore it?

Would having the Magento 2 site in production mode lower mutations and make Address Finder work?

Do I have to tweak these values higher?
```js
    this.millisecondsToIgnoreMutations = 750; // The amount of times the page can mutate in a row without forcing AddressFinder to be reinitialised.
    this.maxMutationTimeoutCount = 20; // The count of the times the page has mutated in a row
```

![image](https://user-images.githubusercontent.com/1968109/76929052-0921e700-6948-11ea-8c5a-e8c840d9bce8.png)

Or is the DOM modified from what AddressFinder expects?

![image](https://user-images.githubusercontent.com/1968109/76929108-366e9500-6948-11ea-9c3d-d77d56ffcc44.png)

I did see a guide for how to fix that if so on the readme.

**Comment by bencorlett** [comment]
Hi @LiamKarlMitchell! This is a warning due to how Magento re-renders the DOM on the page using KnockoutJS while AF is also watching this DOM. Your second screenshot is showing Magento's Knockout templates.

I believe this is to be expected on Magento sites, just due to how their templating system works. It shouldn't have an adverse affect in production, those values are set quite low to catch edge-cases. The autocomplete JS is shared amongst many environments (not just Magento), that's why the warning exists.

@katenorquay, not sure if I missed anything?

**Comment by LiamKarlMitchell** [comment]
Hi @bencorlett  thanks for the speedy reply.
No that makes sense there must be some other reason that it is not working then?
I just thought the Mutations warning might have been a hint as to the reason why.


I just checked the address1 mapping for NZ and it appears to be correct e.g. the selector used in Observer/FormConfig/AddCheckoutShippingAddress.php when I use it with jQuery to toggle the element the input I expect is effected.

```js
jQuery('.form-shipping-address input[name="street[0]"]').toggle()
```

But when I start typing an address no address lookups are coming through and there is no network lookups for autocomplete results.

Any thoughts or a guide on how I can further debug this?

Magento 2.3.2 Development mode.
NZ
Free license.
addressfinder/module-magento2 v1.4.0
Did the rebuild steps, cleared cache/browser cache etc.

![image](https://user-images.githubusercontent.com/1968109/76930672-e7c2fa00-694b-11ea-876f-fb4a9a62a223.png)


Just tried customer address book it does not activate there either.
But the JS files are loaded.
![image](https://user-images.githubusercontent.com/1968109/76931062-c44c7f00-694c-11ea-8d5c-f657be0d9514.png)

**Comment by bencorlett** [comment]
Curious, do you see a similar structure to the following when (via your browser's console) logging `window.AddressFinder`?

![Screen Shot 2020-03-18 at 5 21 17 pm](https://user-images.githubusercontent.com/181919/76931520-f5bd4e80-693c-11ea-8529-217cf18312de.png)

**Comment by LiamKarlMitchell** [comment]
No I don't it is empty, and for some reason says ADDRESSFINDER_DEMO_KEY when that is not the key entered into the back end.

I had put it into Production mode this time.

![image](https://user-images.githubusercontent.com/1968109/76931873-7b95c580-694e-11ea-9a08-ab556311cf99.png)

**Comment by bencorlett** [comment]
Hmm. This is peculiar. Have you by chance copied AF resources (template files, JS, etc) into your own theme? We added [the ability to add custom forms](https://github.com/abletech/addressfinder-magento#supporting-new--customised-forms) in version 1.4.0 and if you've overridden templates, you might have experienced issues potentially?

**Comment by LiamKarlMitchell** [comment]
I have not copied AF resources into my theme and they are not in the parent theme either.

New site with WeltPixel theme and the AddressFinder module installed with Composer.

Ag search in files within app folder for addressfinder only shows up the module being enabled in the config php.
```/opt/containers/sites/devsite/html/app# ag "addressfinder"
etc/config.php
207:        'AddressFinder_AddressFinder' => 1,
```

**Comment by bencorlett** [comment]
Could you modify `app/code/AddressFinder/AddressFinder/view/frontend/templates/plugin.phtml` to look like this?

![Screen Shot 2020-03-18 at 5 47 37 pm 1](https://user-images.githubusercontent.com/181919/76933143-95301080-6940-11ea-9b33-6cf9b618bdea.png)

```javascript
        console.log({
            "widgetConfig": widgetConfig,
            "formsConfig": formsConfig
        });
```

Do you get something like this?

![Screen Shot 2020-03-18 at 5 49 38 pm](https://user-images.githubusercontent.com/181919/76933260-daecd900-6940-11ea-8e5b-1c578ccc3eaf.png)

**Comment by LiamKarlMitchell** [comment]
formsConfig is an empty array
looks equivalent in widgetConfig other than the key and default_country: "nz"

**Comment by LiamKarlMitchell** [comment]
So it's the same problem as before I guess, can't find country.
But it is right there on the form.

![image](https://user-images.githubusercontent.com/1968109/76933949-29a36e80-6953-11ea-9f13-6fd1489a7054.png)

**Comment by LiamKarlMitchell** [comment]
So it is defaulting to AU country when it needs to default to NZ country. #21 

The Magento site is locked down to just NZ with only NZ selected in Allow Countries if that makes any difference?

![image](https://user-images.githubusercontent.com/1968109/76934263-a9c9d400-6953-11ea-9dcf-2e537a8cce7b.png)

I went into the Observer and in its execute method changed the $this->stateMappingProvider->forCountry('AU') to 'NZ' now it appears to work.

Just have to get the domain registered to the license key :)

![image](https://user-images.githubusercontent.com/1968109/76934477-13e27900-6954-11ea-85a7-ce95a7d27ecb.png)


I think these hard coded options need to pull from the configured Default Search Country.

**Comment by bencorlett** [comment]
Good spot. The state mapping with NZ isn’t the issue here, but rather exiting when Australia is disabled as a country. 

Sent from my iPad

Please excuse my brevity

**Comment by LiamKarlMitchell** [comment]
Ah yes, I see that now.
Entries for AU and NZ should only be added if those countries are enabled?

As far as I know Magento does not have region mappings for NZ by default so having it null is fine.
```sql
SELECT * FROM directory_country_region WHERE code = 'NZ'
```
